### ISSUE TITLE
Proposal: Combine efforts with ES-Abstract

### ISSUE THREAD

**Issue by JakeChampion** [domenic/especially#12]
Side-note: I came across this project via [Nicolás Bevacqua's weekly newsletter](https://ponyfoo.com/weekly/1)

This project's goal looks to be the same as @ljharb's [es-abstract](https://github.com/ljharb/es-abstract). I think there may be potential to join your efforts into one project.

**Comment by domenic** [comment]
They have different goals. This one is for writing reference implementations; that one is for writing polyfills.
